# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/postgres:10.4
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: rails5-playground_test
      - image: circleci/redis:4

    working_directory: ~/repo

    environment:
      RAILS_ENV: test
      DATABASE_URL: "postgres://ubuntu@localhost:5432/rails5-playground_test"

    steps:
      - checkout

      # Download and cache dependencies
      - run: sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run rspec
          command: |
            mkdir ~/rspec
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out ~/rspec/rspec.xml \
                            --format progress \

      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/rspec

      - run:
          name: run cucumber
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit \
                                 --out ~/cucumber \
                                 $(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
          when: always
      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber
